#!/usr/bin/env python3
"""Shared helpers for setup-3xui scripts."""

from __future__ import annotations

import base64
import datetime as _dt
import html
import http.cookiejar
import json
import os
import random
import re
import secrets
import ssl
import string
import subprocess
import sys
import urllib.parse
import urllib.request
import uuid
import zipfile
from pathlib import Path
from typing import Any


ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


# Kernel/network tuning borrowed from the setup-vps skill (vless.sh `optimize_network`).
# The official 3X-UI installer does NOT tune the kernel, so a fresh panel node has no
# BBR/buffer tuning out of the box. Applying this drop-in gives the 3X-UI node the same
# open-the-box speed profile as the one-click VLESS script: BBR + fq + enlarged TCP
# buffers + TCP Fast Open + sane keepalive/timeout + memory and file-descriptor limits.
NETWORK_SYSCTL = """# Xray/3X-UI network optimization (borrowed from setup-vps vless.sh)
# TCP optimization
net.core.rmem_default = 262144
net.core.rmem_max = 16777216
net.core.wmem_default = 262144
net.core.wmem_max = 16777216
net.core.netdev_max_backlog = 5000
net.core.netdev_budget = 600
net.ipv4.tcp_rmem = 4096 65536 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_retries2 = 5
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 10240 65535
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_fack = 1
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_adv_win_scale = 2
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.route.flush = 1

# BBR congestion control
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# Memory optimization
vm.swappiness = 10
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5
vm.overcommit_memory = 1

# File descriptor optimization
fs.file-max = 1000000
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches = 524288
"""


# Karing-compatibility subscription adapter. The stock 3X-UI sub server (1) returns 404
# to HEAD requests, which breaks Karing's "check for update" (it shows 更新失败 404), and
# (2) emits `packet-encoding: none` in its Clash YAML, which some Karing builds reject.
# This tiny stdlib reverse proxy sits in front of the sub server: it always GETs upstream
# (so HEAD gets a real status), forwards the client Host (so each node resolves to the real
# server, not 127.0.0.1), and strips packet-encoding from /clash/. The four __PLACEHOLDER__
# values are substituted by deploy_karing_adapter() for the specific panel. RAW string so
# the embedded \n \t \r stay literal in the generated file.
KARING_ADAPTER_PY = r'''#!/usr/bin/env python3
"""Karing-compatibility subscription adapter for 3X-UI (generated by setup-3xui)."""
import http.client
import re
import ssl
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

LISTEN_HOST = "0.0.0.0"
LISTEN_PORT = __LISTEN_PORT__
UPSTREAM_HOST = "127.0.0.1"
UPSTREAM_PORT = __UPSTREAM_PORT__
CERT_FILE = "__CERT_FILE__"
KEY_FILE = "__KEY_FILE__"

# Response headers worth passing back so clients still show traffic/expiry/update info.
PASS_RESP_HEADERS = (
    "content-type",
    "subscription-userinfo",
    "profile-update-interval",
    "profile-title",
    "profile-web-page-url",
    "content-disposition",
)
PACKET_ENCODING_RE = re.compile(rb"^[ \t]*packet-encoding:[ \t]*none[ \t]*\r?\n", re.MULTILINE)

_upstream_ctx = ssl._create_unverified_context()


class Handler(BaseHTTPRequestHandler):
    server_version = "karing-sub-adapter/1.0"
    protocol_version = "HTTP/1.1"

    def _proxy(self):
        # Always GET upstream (upstream 404s on HEAD); shape the response afterwards.
        try:
            conn = http.client.HTTPSConnection(
                UPSTREAM_HOST, UPSTREAM_PORT, timeout=20, context=_upstream_ctx
            )
            # 3X-UI derives each node's address from the request Host header, so the
            # client's Host must reach upstream unchanged; otherwise nodes come back
            # pointing at the adapter's 127.0.0.1 upstream instead of the real server.
            fwd = {}
            for h in ("Host", "User-Agent", "Accept"):
                v = self.headers.get(h)
                if v:
                    fwd[h] = v
            conn.request("GET", self.path, headers=fwd)
            resp = conn.getresponse()
            body = resp.read()
            status = resp.status
            resp_headers = resp.getheaders()
            conn.close()
        except Exception as exc:  # never crash the worker on a bad upstream
            sys.stderr.write("[adapter] upstream error: %r\n" % (exc,))
            try:
                self.send_error(502, "upstream error")
            except Exception:
                pass
            return

        # Fix #2: strip the Karing-incompatible Clash field.
        if "/clash" in self.path.lower():
            body = PACKET_ENCODING_RE.sub(b"", body)

        # Fix #1: HEAD always answers with upstream status (with Content-Length, no body).
        self.send_response(status)
        for k, v in resp_headers:
            if k.lower() in PASS_RESP_HEADERS:
                self.send_header(k, v)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def do_GET(self):
        self._proxy()

    def do_HEAD(self):
        self._proxy()

    def log_message(self, fmt, *args):
        sys.stderr.write("[adapter] " + (fmt % args) + "\n")


def main():
    httpd = ThreadingHTTPServer((LISTEN_HOST, LISTEN_PORT), Handler)
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(CERT_FILE, KEY_FILE)
    httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
    sys.stderr.write(
        "[adapter] listening on %s:%d -> %s:%d\n"
        % (LISTEN_HOST, LISTEN_PORT, UPSTREAM_HOST, UPSTREAM_PORT)
    )
    httpd.serve_forever()


if __name__ == "__main__":
    main()
'''


KARING_ADAPTER_SERVICE = """[Unit]
Description=Karing subscription compatibility adapter for 3X-UI
After=network.target x-ui.service
Wants=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /usr/local/bin/karing-sub-adapter.py
Restart=always
RestartSec=3
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""


def strip_ansi(text: str) -> str:
    return ANSI_RE.sub("", text)


def require_password() -> str:
    password = os.environ.get("VPS_PASSWORD") or os.environ.get("SSH_PASSWORD")
    if not password:
        raise SystemExit("Set VPS_PASSWORD in the environment before running this script.")
    return password


def random_token(length: int = 16) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def expect_ssh(
    *,
    host: str,
    user: str,
    ssh_port: int,
    password: str,
    remote_command: str,
    timeout: int = 1200,
) -> subprocess.CompletedProcess[str]:
    known_hosts = f"/tmp/codex_3xui_known_hosts_{host.replace('.', '_')}_{os.getpid()}"
    expect_script = f"""
set timeout {timeout}
spawn ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile={known_hosts} -p {ssh_port} {user}@{host} {json.dumps(remote_command)}
expect {{
  -re {{password:}} {{ send "$env(VPS_PASSWORD)\\r"; exp_continue }}
  -re {{Please enter your server.*public IPv4 address:}} {{ send "{host}\\r"; exp_continue }}
  -re {{Choose \\[1\\]:}} {{ send "\\r"; exp_continue }}
  -re {{Would you like to customize the Panel Port settings\\?}} {{ send "y\\r"; exp_continue }}
  -re {{Please set up the panel port:}} {{ send "$env(PANEL_PORT)\\r"; exp_continue }}
  -re {{Choose an option \\(default 2 for IP\\):}} {{ send "\\r"; exp_continue }}
  -re {{Do you have an IPv6 address to include\\?}} {{ send "\\r"; exp_continue }}
  -re {{Port to use for ACME HTTP-01 listener.*:}} {{ send "\\r"; exp_continue }}
  -re {{Enter another port for acme\\.sh standalone listener.*:}} {{ send "\\r"; exp_continue }}
  timeout {{ puts "\\nEXPECT_TIMEOUT"; exit 124 }}
  eof
}}
catch wait result
exit [lindex $result 3]
"""
    env = os.environ.copy()
    env["VPS_PASSWORD"] = password
    return subprocess.run(
        ["expect", "-c", expect_script],
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )


def optimize_network(
    *,
    host: str,
    user: str,
    ssh_port: int,
    password: str,
    timeout: int = 120,
) -> subprocess.CompletedProcess[str]:
    """Apply BBR + TCP/memory/fd tuning on the VPS via an idempotent sysctl drop-in.

    Ships NETWORK_SYSCTL as base64 so multi-line content survives the
    repr -> json.dumps -> Tcl -> remote-shell quoting chain without any escaping
    surprises, then reloads sysctl and loads the bbr/fq modules. Re-running it
    just rewrites the same drop-in file, so it is safe to call repeatedly.
    """
    payload = base64.b64encode(NETWORK_SYSCTL.encode("utf-8")).decode("ascii")
    # Order matters: load the bbr/fq modules BEFORE applying sysctl. On stock
    # Ubuntu kernels tcp_bbr is not preloaded (tcp_available_congestion_control
    # shows only "reno cubic"), so applying `tcp_congestion_control = bbr` first
    # could fail. modprobe first guarantees bbr is available when sysctl sets it.
    remote_command = "bash -lc " + repr(
        f"echo '{payload}' | base64 -d > /etc/sysctl.d/99-xray-optimization.conf; "
        "modprobe tcp_bbr >/dev/null 2>&1 || true; "
        "modprobe sch_fq >/dev/null 2>&1 || true; "
        "sysctl --system >/dev/null 2>&1 || "
        "sysctl -p /etc/sysctl.d/99-xray-optimization.conf >/dev/null 2>&1 || true; "
        "echo '----- optimization result -----'; "
        "sysctl net.ipv4.tcp_congestion_control net.core.default_qdisc net.ipv4.tcp_fastopen 2>/dev/null || true; "
        "(lsmod | grep -q '^tcp_bbr' && echo 'tcp_bbr module: loaded') "
        "|| echo 'tcp_bbr module: builtin or unavailable'"
    )
    return expect_ssh(
        host=host,
        user=user,
        ssh_port=ssh_port,
        password=password,
        remote_command=remote_command,
        timeout=timeout,
    )


def deploy_karing_adapter(
    *,
    host: str,
    user: str,
    ssh_port: int,
    password: str,
    session: "PanelSession",
    public_host: str | None = None,
    listen_port: int = 2097,
    timeout: int = 180,
) -> dict[str, Any]:
    """Install the Karing-compatibility subscription adapter and point the panel at it.

    Deploys KARING_ADAPTER_PY as a systemd service on :listen_port (default 2097) in front
    of the 3X-UI sub server (:subPort, default 2096), enables the sub server, and sets
    subURI/subClashURI so the panel hands out :listen_port subscription URLs for every
    client (add_3xui_client.py then emits :listen_port links automatically).

    SAFETY: the adapter owns listen_port; the panel's subPort stays UNCHANGED. NEVER set
    subPort to listen_port -- that collides with the adapter and crash-loops x-ui (which
    drops xray :443 and disconnects customers). Deploying the adapter does not touch xray;
    only the subEnable/subURI DB edit needs a brief x-ui restart (safe on a fresh install).
    Ships everything base64-encoded through the same Tcl-safe path as optimize_network.
    Returns a result dict and never raises; a failed adapter must not fail the install.
    """
    public_host = (public_host or host).strip() or host

    # 1) Read live sub settings so the adapter is templated to THIS panel.
    #    3X-UI 3.4.x moved the settings API under /panel/api/setting/all; older
    #    panels (<=3.2.x) serve it at /panel/setting/all. Try the new path first
    #    and fall back, so the adapter deploys on both.
    settings: dict[str, Any] = {}
    last_exc: Exception | None = None
    for _ep in ("/panel/api/setting/all", "/panel/setting/all"):
        try:
            st = session.post_form(_ep)
        except Exception as exc:
            last_exc = exc
            continue
        if isinstance(st, dict) and st.get("success"):
            settings = st.get("obj") or {}
            break
    else:
        return {"deployed": False, "error": f"could not read panel settings: {last_exc!r}"}

    upstream_port = int(settings.get("subPort") or 2096)
    if listen_port == upstream_port:
        listen_port = upstream_port + 1  # never collide with the sub server
    sub_path = settings.get("subPath") or "/sub/"
    clash_path = settings.get("subClashPath") or "/clash/"
    cert_file = settings.get("subCertFile") or settings.get("webCertFile") or "/root/cert/ip/fullchain.pem"
    key_file = settings.get("subKeyFile") or settings.get("webKeyFile") or "/root/cert/ip/privkey.pem"

    def _as_uri(path: str) -> str:
        p = path if path.startswith("/") else "/" + path
        uri = f"https://{public_host}:{listen_port}{p}"
        return uri if uri.endswith("/") else uri + "/"

    sub_uri = _as_uri(sub_path)
    clash_uri = _as_uri(clash_path)

    # 2) Template the adapter for this panel (RAW-string placeholders -> real values).
    adapter_py = (
        KARING_ADAPTER_PY
        .replace("__LISTEN_PORT__", str(listen_port))
        .replace("__UPSTREAM_PORT__", str(upstream_port))
        .replace("__CERT_FILE__", cert_file)
        .replace("__KEY_FILE__", key_file)
    )

    # 3) DB edit: enable the sub server + advertise the adapter. Only fill cert/key when
    #    the panel has none, so a working cert path is never clobbered.
    pairs: list[tuple[str, str]] = [
        ("subEnable", "true"),
        ("subURI", sub_uri),
        ("subClashURI", clash_uri),
    ]
    if not settings.get("subCertFile"):
        pairs.append(("subCertFile", cert_file))
    if not settings.get("subKeyFile"):
        pairs.append(("subKeyFile", key_file))
    edit_script = (
        "import sqlite3\n"
        "DB = '/etc/x-ui/x-ui.db'\n"
        f"PAIRS = {pairs!r}\n"
        "con = sqlite3.connect(DB, timeout=20)\n"
        "cur = con.cursor()\n"
        "for k, v in PAIRS:\n"
        "    cur.execute('UPDATE settings SET value=? WHERE key=?', (v, k))\n"
        "    if cur.rowcount == 0:\n"
        "        cur.execute('INSERT INTO settings (key,value) VALUES (?,?)', (k, v))\n"
        "con.commit()\n"
        "rows = [list(r) for r in cur.execute(\"SELECT key,value FROM settings WHERE key IN ('subEnable','subURI','subClashURI')\").fetchall()]\n"
        "print('KARING_DB_OK', rows)\n"
        "con.close()\n"
    )

    py_b64 = base64.b64encode(adapter_py.encode("utf-8")).decode("ascii")
    svc_b64 = base64.b64encode(KARING_ADAPTER_SERVICE.encode("utf-8")).decode("ascii")
    edit_b64 = base64.b64encode(edit_script.encode("utf-8")).decode("ascii")

    # 4) One Tcl/bash-safe remote orchestration (base64 blobs + single-quoted patterns;
    #    no $ [ ] backtick backslash). Deploy adapter -> enable+start -> open ufw if active
    #    -> stop x-ui, back up db, enable sub + set subURI, start x-ui -> verify ports.
    lp = str(listen_port)
    up = str(upstream_port)
    hc_url = "https://127.0.0.1:" + lp + "/" + sub_path.strip("/") + "/healthcheck"
    cmd = (
        "echo '" + py_b64 + "' | base64 -d > /usr/local/bin/karing-sub-adapter.py; "
        "chmod +x /usr/local/bin/karing-sub-adapter.py; "
        "echo '" + svc_b64 + "' | base64 -d > /etc/systemd/system/karing-sub-adapter.service; "
        "echo '" + edit_b64 + "' | base64 -d > /tmp/karing_set_sub.py; "
        "echo '== CERT =='; (test -f '" + cert_file + "' && test -f '" + key_file + "' && echo CERT_OK || echo CERT_MISSING); "
        "systemctl daemon-reload; "
        "systemctl enable karing-sub-adapter >/dev/null 2>&1; "
        "systemctl restart karing-sub-adapter; "  # restart (not just start) so a re-run reloads the fresh file
        "(ufw status 2>/dev/null | grep -qi 'status: active' && ufw allow " + lp + "/tcp >/dev/null 2>&1 && echo UFW_OPENED || echo UFW_SKIP); "
        "sleep 2; "
        "echo '== set subURI (brief x-ui restart) =='; "
        "systemctl stop x-ui; "
        "cp /etc/x-ui/x-ui.db /etc/x-ui/x-ui.db.bak-karing-adapter; "
        "python3 /tmp/karing_set_sub.py; "
        "systemctl start x-ui; "
        "sleep 4; "
        "echo '== adapter active =='; systemctl is-active karing-sub-adapter; "
        "echo '== x-ui active =='; systemctl is-active x-ui; "
        "echo '== adapter port =='; (ss -ltn 2>/dev/null | grep ':" + lp + "' || echo ADAPTER_PORT_DOWN); "
        "echo '== sub port =='; (ss -ltn 2>/dev/null | grep ':" + up + "' || echo SUB_PORT_DOWN); "
        "echo '== healthcheck =='; curl -k -sI " + hc_url + " 2>&1 | head -1"
    )
    remote_command = "bash -lc " + repr(cmd)
    res = expect_ssh(
        host=host, user=user, ssh_port=ssh_port, password=password,
        remote_command=remote_command, timeout=timeout,
    )
    out = res.stdout or ""
    # expect echoes the FULL spawned command (which literally contains our CERT_OK /
    # ADAPTER_PORT_DOWN / UFW_OPENED markers as echo arguments) on its "spawn ssh ..."
    # line. Strip that line so each marker is detected only where the remote shell
    # actually printed it, not where it merely appears inside the command text.
    scan = "\n".join(ln for ln in out.splitlines() if not ln.lstrip().startswith("spawn "))

    cert_ok = "CERT_OK" in scan
    db_ok = "KARING_DB_OK" in scan
    adapter_port_up = "ADAPTER_PORT_DOWN" not in scan
    sub_port_up = "SUB_PORT_DOWN" not in scan
    return {
        "deployed": res.returncode == 0 and cert_ok and db_ok and adapter_port_up and sub_port_up,
        "listenPort": listen_port,
        "upstreamPort": upstream_port,
        "subURI": sub_uri,
        "subClashURI": clash_uri,
        "certFile": cert_file,
        "keyFile": key_file,
        "certPresent": cert_ok,
        "subEnabled": db_ok,
        "adapterPortListening": adapter_port_up,
        "subPortListening": sub_port_up,
        "ufwOpened": "UFW_OPENED" in scan,
        "dbBackup": "/etc/x-ui/x-ui.db.bak-karing-adapter",
        "log": out,
    }


def parse_panel_install_log(log_text: str) -> dict[str, Any]:
    clean = strip_ansi(log_text)
    patterns = {
        "username": r"Username:\s*([^\s]+)",
        "password": r"Password:\s*([^\s]+)",
        "port": r"Port:\s*([0-9]+)",
        "web_base_path": r"WebBasePath:\s*([^\s]+)",
        "access_url": r"Access URL:\s*(https?://[^\s]+)",
        "api_token": r"API Token:\s*([^\s]+)",
        "database": r"Database:\s*(.+)",
    }
    info: dict[str, Any] = {}
    for key, pattern in patterns.items():
        match = re.search(pattern, clean)
        if match:
            info[key] = match.group(1).strip()
    if "port" in info:
        info["port"] = int(info["port"])
    if "web_base_path" in info:
        path = info["web_base_path"]
        info["web_base_path"] = "/" + path.strip("/") + "/"
    required = ["username", "password", "port", "web_base_path", "access_url"]
    missing = [key for key in required if not info.get(key)]
    if missing:
        raise ValueError(f"Could not parse panel install log. Missing: {', '.join(missing)}")
    return info


class PanelSession:
    def __init__(self, base_url: str, username: str, password: str) -> None:
        self.base_url = base_url.rstrip("/")
        self.username = username
        self.password = password
        self.cookiejar = http.cookiejar.CookieJar()
        self.opener = urllib.request.build_opener(
            urllib.request.HTTPSHandler(context=ssl._create_unverified_context()),
            urllib.request.HTTPCookieProcessor(self.cookiejar),
        )
        self.csrf_token = ""

    def _request(
        self,
        method: str,
        path: str,
        data: Any | None = None,
        *,
        json_body: bool = False,
        csrf: bool = False,
    ) -> Any:
        url = self.base_url + path
        body = None
        headers = {"X-Requested-With": "XMLHttpRequest"}
        if csrf and self.csrf_token:
            headers["X-CSRF-Token"] = self.csrf_token
        if data is not None:
            if json_body:
                body = json.dumps(data).encode("utf-8")
                headers["Content-Type"] = "application/json"
            else:
                body = urllib.parse.urlencode(data).encode("utf-8")
                headers["Content-Type"] = "application/x-www-form-urlencoded; charset=UTF-8"
        req = urllib.request.Request(url, data=body, headers=headers, method=method)
        with self.opener.open(req, timeout=45) as resp:
            text = resp.read().decode("utf-8", "replace")
            ctype = resp.headers.get("content-type", "")
        if "json" in ctype or text.startswith("{") or text.startswith("["):
            return json.loads(text)
        return text

    def login(self) -> None:
        html_text = self._request("GET", "/")
        match = re.search(r'name="csrf-token" content="([^"]+)"', html_text)
        if match:
            self.csrf_token = match.group(1)
        result = self._request(
            "POST",
            "/login",
            {"username": self.username, "password": self.password},
            csrf=True,
        )
        if not isinstance(result, dict) or not result.get("success"):
            raise RuntimeError(f"3X-UI login failed: {result}")
        try:
            token = self._request("GET", "/csrf-token")
            if isinstance(token, dict) and token.get("success") and token.get("obj"):
                self.csrf_token = token["obj"]
        except Exception:
            pass

    def get(self, path: str) -> Any:
        return self._request("GET", path)

    def post_form(self, path: str, data: dict[str, Any] | None = None) -> Any:
        return self._request("POST", path, data or {}, csrf=True)

    def post_json(self, path: str, data: dict[str, Any] | list[Any] | None = None) -> Any:
        return self._request("POST", path, data or {}, json_body=True, csrf=True)


def load_panel_info(path: Path) -> dict[str, Any]:
    info = json.loads(path.read_text(encoding="utf-8"))
    panel = info.get("panel", info)
    for key in ["url", "username", "password"]:
        if not panel.get(key):
            raise ValueError(f"panel-info JSON missing panel.{key}")
    return info


def panel_session_from_info(info: dict[str, Any]) -> PanelSession:
    panel = info.get("panel", info)
    session = PanelSession(panel["url"], panel["username"], panel["password"])
    session.login()
    return session


def default_vless_reality_payload(host: str, inbound_port: int, remark: str, keys: dict[str, str]) -> dict[str, Any]:
    short_id = secrets.token_hex(4)
    settings = {
        "clients": [],
        "decryption": "none",
        "encryption": "none",
        "fallbacks": [],
    }
    stream_settings = {
        "network": "tcp",
        "security": "reality",
        "tcpSettings": {
            "acceptProxyProtocol": False,
            "header": {"type": "none"},
        },
        "realitySettings": {
            "show": False,
            "xver": 0,
            "target": "www.nvidia.com:443",
            "serverNames": ["www.nvidia.com"],
            "privateKey": keys["privateKey"],
            "minClientVer": "",
            "maxClientVer": "",
            "maxTimediff": 0,
            "shortIds": [short_id],
            "mldsa65Seed": "",
            "settings": {
                "publicKey": keys["publicKey"],
                "fingerprint": "chrome",
                "serverName": "",
                "spiderX": "/",
                "mldsa65Verify": "",
            },
        },
    }
    return {
        "up": 0,
        "down": 0,
        "total": 0,
        "remark": remark or f"US-Reality-{host}",
        "enable": "true",
        "expiryTime": 0,
        "trafficReset": "never",
        "lastTrafficResetTime": 0,
        "listen": "",
        "port": inbound_port,
        "protocol": "vless",
        "settings": json.dumps(settings, separators=(",", ":")),
        "streamSettings": json.dumps(stream_settings, separators=(",", ":")),
        "sniffing": json.dumps({"enabled": False}, separators=(",", ":")),
        "tag": "",
    }


def ensure_default_inbound(session: PanelSession, host: str, inbound_port: int, remark: str) -> dict[str, Any]:
    options = session.get("/panel/api/inbounds/options")
    if isinstance(options, dict) and options.get("success"):
        for item in options.get("obj") or []:
            if item.get("protocol") == "vless" and int(item.get("port") or 0) == inbound_port:
                return {"created": False, "inbound": item}
    keys = session.get("/panel/api/server/getNewX25519Cert")
    if not isinstance(keys, dict) or not keys.get("success"):
        raise RuntimeError(f"Could not generate Reality keys: {keys}")
    payload = default_vless_reality_payload(host, inbound_port, remark, keys["obj"])
    result = session.post_form("/panel/api/inbounds/add", payload)
    if not isinstance(result, dict) or not result.get("success"):
        raise RuntimeError(f"Could not create VLESS Reality inbound: {result}")
    inbound = result.get("obj") or {}
    return {"created": True, "inbound": inbound, "payload": payload}


def select_inbound(session: PanelSession, inbound_id: int | None = None, inbound_port: int | None = None) -> dict[str, Any]:
    options = session.get("/panel/api/inbounds/options")
    if not isinstance(options, dict) or not options.get("success"):
        raise RuntimeError(f"Could not list inbounds: {options}")
    inbounds = options.get("obj") or []
    if inbound_id is not None:
        for inbound in inbounds:
            if int(inbound.get("id")) == inbound_id:
                return inbound
        raise RuntimeError(f"Inbound id {inbound_id} was not found.")
    if inbound_port is not None:
        for inbound in inbounds:
            if int(inbound.get("port") or 0) == inbound_port and inbound.get("protocol") == "vless":
                return inbound
    for inbound in inbounds:
        if inbound.get("protocol") == "vless":
            return inbound
    if inbounds:
        return inbounds[0]
    raise RuntimeError("No inbound exists. Create a VLESS Reality inbound first.")


def parse_duration_to_expiry(duration: str | None = None, days: int | None = None, expires_at: str | None = None) -> int:
    if expires_at:
        value = expires_at.strip()
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
            dt = _dt.datetime.fromisoformat(value + "T23:59:59")
        else:
            dt = _dt.datetime.fromisoformat(value)
        return int(dt.timestamp() * 1000)
    if days is not None:
        return int((_dt.datetime.now() + _dt.timedelta(days=days)).timestamp() * 1000)
    if not duration:
        return 0
    text = duration.strip().lower()
    if text in {"0", "none", "unlimited", "永久", "不限", "无限"}:
        return 0
    match = re.search(r"(\d+)\s*(天|日|day|days|d)", text)
    if match:
        return parse_duration_to_expiry(days=int(match.group(1)))
    match = re.search(r"(\d+)\s*(周|星期|week|weeks|w)", text)
    if match:
        return parse_duration_to_expiry(days=int(match.group(1)) * 7)
    match = re.search(r"(\d+)\s*(月|个月|month|months|m)", text)
    if match:
        return parse_duration_to_expiry(days=int(match.group(1)) * 30)
    match = re.search(r"(\d+)\s*(年|year|years|y)", text)
    if match:
        return parse_duration_to_expiry(days=int(match.group(1)) * 365)
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", text):
        return parse_duration_to_expiry(expires_at=text)
    raise ValueError(f"Unsupported duration: {duration}")


def add_client_payload(
    *,
    client_name: str,
    inbound_ids: list[int],
    expiry_time: int,
    total_gb: float = 0,
    comment: str = "",
    group: str = "",
    flow: str = "xtls-rprx-vision",
) -> dict[str, Any]:
    return {
        "client": {
            "email": client_name,
            "subId": random_token(16).lower(),
            "id": str(uuid.uuid4()),
            "password": random_token(16),
            "auth": random_token(16),
            "flow": flow,
            "security": "auto",
            "totalGB": int(total_gb * 1024 * 1024 * 1024) if total_gb else 0,
            "expiryTime": expiry_time,
            "reset": 0,
            "limitIp": 0,
            "tgId": 0,
            "group": group,
            "comment": comment,
            "enable": True,
        },
        "inboundIds": inbound_ids,
    }


def parse_jsonish(value: Any) -> Any:
    if isinstance(value, str):
        return json.loads(value) if value.strip() else {}
    return value or {}


def vless_link_from_inbound(inbound: dict[str, Any], client: dict[str, Any], host: str) -> str:
    settings = parse_jsonish(inbound.get("settings"))
    stream = parse_jsonish(inbound.get("streamSettings"))
    reality = stream.get("realitySettings") or {}
    reality_settings = reality.get("settings") or {}
    target = reality.get("target") or "www.nvidia.com:443"
    sni = reality_settings.get("serverName") or (reality.get("serverNames") or [target.split(":")[0]])[0]
    short_ids = reality.get("shortIds") or [""]
    encryption = settings.get("encryption") or "none"
    client_id = client.get("id") or client.get("uuid")
    if not client_id:
        raise RuntimeError(f"Client has no UUID/id: {client}")
    remark = f"{inbound.get('remark') or 'VLESS'}-{client.get('email') or client_id}"
    params = {
        "type": stream.get("network") or "tcp",
        "encryption": encryption,
        "security": stream.get("security") or "none",
        "sni": sni,
        "fp": reality_settings.get("fingerprint") or "chrome",
        "pbk": reality_settings.get("publicKey") or "",
        "sid": short_ids[0] if short_ids else "",
        "spx": reality_settings.get("spiderX") or "/",
    }
    flow = client.get("flow")
    if flow:
        params["flow"] = flow
    query = urllib.parse.urlencode(params, safe="/")
    return f"vless://{client_id}@{host}:{inbound.get('port')}?{query}#{urllib.parse.quote(remark)}"


def write_qr_png(text: str, output_path: Path) -> None:
    try:
        import segno  # type: ignore
    except Exception:
        subprocess.run([sys.executable, "-m", "pip", "install", "--user", "--quiet", "segno"], check=True)
        import segno  # type: ignore
    qr = segno.make(text, error="m")
    qr.save(output_path, scale=8, border=3)


def xml_escape(text: Any) -> str:
    return html.escape("" if text is None else str(text), quote=True)


def docx_paragraph(text: str, *, bold: bool = False) -> str:
    safe = xml_escape(text)
    bold_xml = "<w:b/>" if bold else ""
    return (
        "<w:p><w:r><w:rPr>"
        f"{bold_xml}"
        "</w:rPr><w:t xml:space=\"preserve\">"
        f"{safe}"
        "</w:t></w:r></w:p>"
    )


def write_management_docx(
    *,
    output_path: Path,
    title: str,
    fields: list[tuple[str, Any]],
    notes: list[str] | None = None,
) -> None:
    paragraphs = [docx_paragraph(title, bold=True), docx_paragraph("")]
    for key, value in fields:
        paragraphs.append(docx_paragraph(f"{key}: {value}"))
    if notes:
        paragraphs.append(docx_paragraph(""))
        paragraphs.append(docx_paragraph("注意事项", bold=True))
        for note in notes:
            paragraphs.append(docx_paragraph(f"- {note}"))
    document_xml = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    {''.join(paragraphs)}
    <w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
  </w:body>
</w:document>
"""
    content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>
"""
    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("word/document.xml", document_xml)


def archive_management_doc(
    src: Path,
    server_label: str,
    archive_dir: str = "~/Documents/VPS",
) -> Path | None:
    """Drop a second, meaningfully named copy of a management .docx into a stable folder.

    The per-run output folder keeps its own `3xui-management.docx`; this copies it to
    `<archive_dir>/<server_label>-3X-UI后台资料.docx` so every server's backend doc
    collects in one place (default ~/Documents/VPS). Returns the destination path, or
    None if archiving was skipped/failed (never fatal to the install).
    """
    try:
        dest_dir = Path(archive_dir).expanduser()
        dest_dir.mkdir(parents=True, exist_ok=True)
        safe = re.sub(r'[\\/:*?"<>|]+', "_", str(server_label or "3X-UI").strip()).strip("._- ") or "3X-UI"
        dest = dest_dir / f"{safe}-3X-UI后台资料.docx"
        dest.write_bytes(Path(src).read_bytes())
        return dest
    except Exception:
        return None

